name: collage2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  qr_code_scanner: any
  fluttertoast: any
  toast: any
  file_picker: 1.4.3+1
  url_launcher: any
  flutter_linkify: any
  firebase_database: any
  firebase_auth: any
  firebase_core: any
  cloud_firestore: any
  firebase_storage: any
  shared_preferences: any
  path_provider: any
  http: any
  carousel_slider: any
  carousel_pro: any
  fluttie: any
  flutter_lottie: any
  lottie_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true 


flutter:
  uses-material-design: true
  assets:
    - image_gif/animi.json
    - image_gif/
    